// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaJZ8wAiA15GUKzZUKkxDbE5T1Dm1EsVE',
    appId: '1:980765740693:web:8e6c07e31616391a6c959c',
    messagingSenderId: '980765740693',
    projectId: 'flutter-upsightdemo',
    authDomain: 'flutter-upsightdemo.firebaseapp.com',
    storageBucket: 'flutter-upsightdemo.appspot.com',
    measurementId: 'G-H6QZ2NLDHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSddTMOgFpArQYHWmyYTybPNJXSXWrNqk',
    appId: '1:980765740693:android:1621ea8819a2ecce6c959c',
    messagingSenderId: '980765740693',
    projectId: 'flutter-upsightdemo',
    storageBucket: 'flutter-upsightdemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9XS-2MWilsyq4z7GtFXIYljWtMez9nhY',
    appId: '1:980765740693:ios:b2e36779002d55836c959c',
    messagingSenderId: '980765740693',
    projectId: 'flutter-upsightdemo',
    storageBucket: 'flutter-upsightdemo.appspot.com',
    iosClientId: '980765740693-lldbfc4968nc95rosrkd4h8hqeu99m44.apps.googleusercontent.com',
    iosBundleId: 'com.example.boardProject',
  );
}

ddddddddd